version: '3'
services:
  database:
    image: "postgres:13.3-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=syspass
      - POSTGRES_USER=Master
      - POSTGRES_DB=events
    volumes:
      - ./_data-dev/postgres-data:/var/lib/postgresql/data